import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { clerkConfig } from "./clerk-config";
import Header from "@/components/Header";
import VAPIFloatingAssistant from "@/components/VAPIFloatingAssistant";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider 
          dynamic
          signInUrl={clerkConfig.signInUrl}
          signUpUrl={clerkConfig.signUpUrl}
          afterSignInUrl={clerkConfig.afterSignInUrl}
          afterSignUpUrl={clerkConfig.afterSignUpUrl}
        >
          <ConvexClientProvider>
            <Header/>
            <main>{children}</main>
            <VAPIFloatingAssistant />
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
