// Complete South African Universities Database - All 26 Universities

export interface University {
  name: string;
  shortName: string;
  position: [number, number, number];
  color: string;
  province: string;
  city: string;
  established: number;
  type: "Traditional University" | "Comprehensive University" | "University of Technology";
  description: string;
  specializations: string[];
  ranking: string;
  students: string;
  climate: string;
  avgTemp: { summer: string; winter: string };
  weather: { temp: string; condition: string; humidity: string; wind: string };
  admissionRequirements: {
    undergraduate: string;
    postgraduate: string;
    applicationDeadline: string;
  };
  fees: { undergraduate: string; postgraduate: string };
  accommodation: string;
  highlights: string[];
  bestFor: string;
  campusLife: string;
  studentSupport: string[];
  notableFacts: string[];
  coordinates: { lat: number; lng: number };
}

export const SA_UNIVERSITIES: University[] = [
  // TRADITIONAL UNIVERSITIES (11)
  { name: "University of Cape Town", shortName: "UCT", position: [-15, 0, -10], color: "#1e40af", province: "Western Cape", city: "Cape Town", established: 1829, type: "Traditional University", description: "Africa's leading research university", specializations: ["Medicine", "Engineering", "Business", "Law"], ranking: "#1 in Africa", students: "29,000+", climate: "Mediterranean", avgTemp: { summer: "26°C", winter: "15°C" }, weather: { temp: "22°C", condition: "Sunny", humidity: "65%", wind: "15 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R65,000 - R85,000/year", postgraduate: "R45,000 - R120,000/year" }, accommodation: "On-campus residences available", highlights: ["🏆 Top-ranked African university", "🔬 Leading research output", "🏔️ Table Mountain views", "🌊 Close to beaches"], bestFor: "Research excellence, Medicine, International recognition", campusLife: "Vibrant cosmopolitan campus with mountain and ocean access", studentSupport: ["Financial aid", "Career services", "Academic support"], notableFacts: ["Oldest university in South Africa", "Most beautiful campus globally"], coordinates: { lat: -33.9577, lng: 18.4612 } },
  
  { name: "University of Fort Hare", shortName: "UFH", position: [-10, 0, 15], color: "#059669", province: "Eastern Cape", city: "Alice", established: 1916, type: "Traditional University", description: "Historic 'Oxford of Africa'", specializations: ["Law", "Education", "Agriculture", "Social Sciences"], ranking: "Historic significance", students: "12,000+", climate: "Temperate", avgTemp: { summer: "24°C", winter: "12°C" }, weather: { temp: "18°C", condition: "Partly Cloudy", humidity: "70%", wind: "10 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R35,000 - R45,000/year", postgraduate: "R25,000 - R55,000/year" }, accommodation: "On-campus residences", highlights: ["🎓 Alma mater of Mandela", "📚 Liberation history", "🌍 Pan-African heritage"], bestFor: "Law, Education, African studies", campusLife: "Small town with rich political history", studentSupport: ["NSFAS funding", "Academic mentoring"], notableFacts: ["Produced many African leaders", "First to admit black students"], coordinates: { lat: -32.7833, lng: 26.8500 } },
  
  { name: "University of the Free State", shortName: "UFS", position: [0, 0, 10], color: "#dc2626", province: "Free State", city: "Bloemfontein", established: 1904, type: "Traditional University", description: "Central SA university with agriculture focus", specializations: ["Agriculture", "Medicine", "Law", "Education"], ranking: "Top 5 for Agriculture", students: "37,000+", climate: "Semi-arid", avgTemp: { summer: "28°C", winter: "10°C" }, weather: { temp: "16°C", condition: "Clear", humidity: "40%", wind: "18 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R45,000 - R65,000/year", postgraduate: "R30,000 - R75,000/year" }, accommodation: "Extensive on-campus residences", highlights: ["🌾 Leading agricultural research", "⚖️ Strong law faculty", "🏥 Medical school"], bestFor: "Agriculture, Medicine, Central location} }
];7499 24.lng:  -28.7282, at: lnates: {e"], coordi Sol Plaatjer aftamed"Nsity", erewest univ ["Second nableFacts:"], notechnology"Modern trams", "New progt: [uppordentS, stu" new campusrand"BcampusLife: ograms",  prciences, Newn, Data s"Educatioor: tFces"], besData scien", "📊 nd cityDiamo"💎 , nsive"ehet comprewes N ["🌟lights: high",cespus residen "New camcommodation:}, ac" /yearR45,00000 - "R20,0: teraduastg", po000/year R38,R28,000 -e: "raduates: { underg" }, feSeptember"30 ine: ationDeadlapplicication", ant qualif: "Relevuate", postgradelor's passith Bach we: "NSCatundergraduents: { emuirsionReq admish" },km/6 , wind: "1": "35%midity"Dry", hun: ", conditiomp: "20°Ceather: { te" }, w: "12°Cnter"30°C", wi: { summer: avgTemp, rid""Semi-a:  climate00+",,0nts: "3tudems", sprograative ovNew inn"nking: ences"], ra "Data Scies","Humanitiiences", Scl , "Naturaation"ons: ["Educecializatiersity", spnivnsive uw compreheon: "Ne descriptilogy",of Technoniversity "U, type: 2014ished: establrley", y: "Kimbe", citCape"Northern  , province:80c"ea5lor: "#0, 18], cotion: [-8, ", positName: "SPUty", shorUniversiSol Plaatje "ame:  n  {,
  
9694 } }0.53, lng: 3lat: -25.47ates: { "], coordindevelopmential inc"Proversity", ivwest unFacts: ["Ne], notablelities"ern facis", "Modw program"NentSupport: [ studeampus",ew modern cfe: "N, campusLirams"New proggriculture, : "A], bestFores"ti facili Modern "⚙️ focus",uralriculty", "🌾 Agst universitNewehts: ["🌱 ghlig, hiresidences"s mpu"New can: commodatio" }, ac48,000/year- RR22,000  "tgraduate:pos/year", 00 - R42,000R30,0e: "ndergraduatees: { u }, feptember""30 Sdline: tionDeaicapl, apn"tio qualifica "Relevantte:raduastg pass", poiplomaC with Date: "NSdu{ undergrats: menreissionRequi, adm"9 km/h" }ind: ", w%58ty: "idi hum",Pleasantition: "cond", emp: "23°Cweather: { t18°C" }, , winter: " "28°C"summer:vgTemp: { opical", ae: "Subtrat clim0+",ents: "5,00", studmsogragrowing prth ew winking: "Nion"], raatEduc"IT", "ng", eeringin", "Eture"Agriculizations: [special", universitytechnology  "Newest ion:cript des",logyy of Technoitersnive: "U2014, typstablished: spruit", eel"Nga", city: analumince: "Mprovc2626", p#dlor: ", 0, 14], coion: [8osit: "UMP", pmeortNa, sh"malangaf Mpuniversity o"U
  { name: } },
  g: 27.8333 67, ln lat: -26.71es: {atordinions"], coectring connactus", "Manufustrial focu"Strong indbleFacts: [g"], notaal trainin, "Technics"shipertrial partnInduspport: ["studentSun campus",  regioialtrInduspusLife: "ng", camManufacturing,  engineeri"Industrial, bestFor:  skills"]calcti Pra", "🔧ogramsering prEngine"⚙️ ", nsnectiodustrial con In"🏭ghts: [, highliresidences"Campus on: "modaticcomar" }, a4,000/ye R50 -5,00R2raduate: "postg/year", R46,0000 - : "R34,00ergraduates: { undee }, ftember"Sep: "30 nelitionDeadapplicaication", vant qualif "Relee:ostgraduat, poma pass"ith Diplate: "NSC w{ undergraduments: ssionRequiremi" }, adm/hwind: "13 k",  "48%, humidity:n: "Mild", conditio"18°C"{ temp: , weather: " }: "14°C", wintermmer: "26°C { suavgTemp:land", ightropical he: "Subat0+", climts: "20,00 studenrial",g in indust"Stronking: "], ranciencesgement S", "Mana "IT",inggineertions: ["En, specializa"rsityogy univechnoltrial te "Induson:ptigy", descrilo Technosity ofe: "Univer typshed: 1966,k", establiaranderbijlp city: "VGauteng","ovince: 059669", prlor: "#co [2, 0, 6], n:tio posi",ame: "VUTy", shortNchnolog Tesity of Univerme: "Vaal
  { na
  2314 } },45, lng: 28.at: -25.75nates: { l"], coordile campusesMultip, "hnology" of Tec Universityargest"LleFacts: [tabps"], nopartnershidustry g", "In trainin"Technical [pport:tSuty", studens universiti-campue mul"Largfe:  campusLiT, Arts", Iechnology, tineeringEng"stFor: ign"], be🎨 Arts & desing", "ngineer, "⚙️ Es"puseMultiple cam: ["🏢 , highlightsresidences"ampus iple cion: "Mult accommodat/year" },00 - R58,000 "R26,0tgraduate: posr",48,000/yea R"R36,000 -duate:  { undergra fees:tember" },Sep30 dline: "ionDeaatic applfication",ualilevant qate: "Redurastg, poss"oma pah Dipl witduate: "NSCundergra{ irements: ssionRequ, admi" }10 km/h "wind:, "idity: "50%t", humsan "Pleaondition:, c "21°C"er: { temp:}, weath°C" er: "16int w°C",mmer: "26sugTemp: { hland", av higalbtropic"Su: ", climate000+dents: "60,", stullmentgest by enroLar " ranking:sign"],rts & De"A", nt "Manageme, "IT",ing"neerEngiations: ["aliz", speci universityechnologylti-campus t"Large muscription: gy", deechnoloity of T: "Univers04, typeished: 20ia", establretorty: "Puteng", cince: "Gaovid12", pr#7c2 color: " 2],: [6, 0,", position"TUTe: ortNam, sh"hnology Tecniversity ofe Uwanme: "Tsh
  { na,
  } }3 ng: 30.883 -29.9667, l{ lat:oordinates: , ct"]l developmens", "Locacuy founit commtrongeFacts: ["Stabl nog"],cal trainin", "Techni programsty"Communipport: [entSu, studcampus"tered -cen "CommunityLife:mpus", caEngineering, echnology tty"CommunitFor: "], beslopment devecalms", "🌍 Loprogragineering ⚙️ En", "cusfoy "🤝 Communitts: [hlighces", higdenampus resin: "Ccommodatior" }, ac2,000/yeaR24,000 - R5ate: "ostgradur", p000/yea - R45,,000te: "R32ndergradua{ u: esr" }, febe "30 Septemne:tionDeadli", applicacationfivant qualile "Retgraduate:s", posloma pas with DipSCraduate: "N{ undergts: Requiremension, admis/h" }ind: "11 km: "72%", w", humidity"Warm condition:"24°C", : ther: { temp}, wea" nter: "20°C"28°C", wisummer: { vgTemp: opical", a"Subtrimate: 2,000+", cl"1dents:  stulogy",echnowing tg: "Groankin"], rt Sciences "Managemen "IT",eering","Enginations: [ specializsity",ogy univernolch teused-focCommunity "iption:", descr Technologyiversity of, type: "Un79ed: 19stablishUmlazi", e", city: "Natalu-: "KwaZulrovince", p "#059669 color:],0, 2: [16,  position",e: "MUTshortNam", echnologyrsity of Tsuthu Univeame: "Mango
  { n8 } },
   31.02187, lng:: -29.85 lats: { coordinateus"],Coastal focctions", " conneong industrys: ["StrtableFactg"], no trainin "Practicalrships",partne"Industry : [tSupport studenmpus",oastal ca c"ModernampusLife: le", ctal lifestyoasology, Cering techninengFor: "Es"], bestershippartnndustry "🏭 Iams", rogrg pneeringi⚙️ Enon", "ocatiastal l"🌊 Cos: [ghlightences", his residion: "Campucommodatr" }, ac/yea - R60,000e: "R26,000graduatr", postea0/y R52,00 "R38,000 -ergraduate: { unds:er" }, feeptembe: "30 SeinionDeadl, applicatlification"uaelevant qaduate: "R", postgra passh Diplom"NSC wite: raduatts: { undergquiremenissionRe, adm2 km/h" } wind: "1",ity: "75%", humid"Humidndition: "25°C", co her: { temp:}, weat" 20°C winter: ""28°C",mer: { sumavgTemp: ical", Subtrop: "mate, cli "29,000+" students:KZN",Leading in ranking: ""], ncesScie"Applied nt", geme", "ManaIT", "eeringgin["Enizations: ecial", spsityvergy uniechnolostal tn: "Coariptiology", descof Technoiversity ype: "Un002, ttablished: 2an", esy: "DurbNatal", citZulu-"Kwa: ce, provin7c3aed"lor: "# 0, 4], co [14, position:",tName: "DUTlogy", shorf Technoiversity o "Durban Uname:
  { n,
  26.2167 } } lng:  -29.1167,es: { lat:inatordation"], coal loctren"Cfocus", ical g techn"Strons: [actleF], notabnerships"art pIndustryng", "al traini"Technict: [ntSupporstude", sed campuslogy-focu"TechnopusLife:  camskills",actical y, IT, Prchnologineering te "Engor:le"], bestFrdab"💰 Affo", itiescil "💻 IT fanology",ing techneer Engi["⚙️: ghlightsences", hi resid"Campus: ioncommodat }, ac0/year"R55,00- "R25,000 duate: grayear", post00/,000 - R50,0 "R35uate: { undergradr" }, fees:0 Septembe"3: onDeadline", applicatiion qualificatevantRel "e:atradupostg pass", ma with Diplo: "NSCgraduatederents: { unionRequiremss admikm/h" },"18 ", wind: "40%dity: r", humi"Cleation: di", con"16°C: { temp: eather0°C" }, wr: "1nte"28°C", wi { summer: ", avgTemp:dSemi-arimate: "li4,000+", cdents: "1ering", stung in engineking: "Stros"], ranScience, "Health nagement""MaT", ng", "Iineering"Etions: [, specializa"niversityology utechnntral ion: "Ceriptogy", descof Technolniversity pe: "U1, ty: 198lishedn", estabfonteiem: "Blo, cityate"Free St"e: incov626", prdc2color: "# 0, 12], : [2,sition "CUT", poortName:ology", shity of Technverstral Uni "Cename: { n } },
  
 4241 18.249, lng: -33.9tes: { lat:ordinaons"], connectiIndustry co", "chnologyty of Tesiverest Unis: ["LargeFact"], notabltrainingical "Practships", tnertry par"Induspport: [", studentSususey campologchnModern teife: "usLgn", camp, Desi, ITlogychnoing te"EngineerbestFor: puses"], ple cam🏙️ Multi "esign", and d💻 IT, "grams"proechnology  ["⚙️ Thts: highliges",esidencus rampon: "Ccommodati, ac }000/year"- R65,8,000 te: "R2tgradua", posyear R55,000/0 -"R40,00ate: radu: { undergr" }, fees0 Septembeeadline: "3ionD", applicatationifical"Relevant quuate: adstgr", poa pass DiplomC with "NSate:radu: { undergmentsonRequiremissih" }, adm/ind: "15 k"65%", w , humidity:n: "Sunny"ionditC", coemp: "22°er: { t}, weath: "15°C" °C", winter"26 summer: , avgTemp: {terranean": "Mediimate2,000+", cl "3s:entstudlogy", echnof Trsity op Univeking: "To], ranBusiness"ign", "", "DesITring", "ngineetions: ["Ecializa, spersity"gy univeechnolo"Leading tion: ript", descology of Technersitype: "Univ05, tyhed: 20, establisown""Cape T", city: apetern C: "Wesrovincec", p"#ea5808], color: 8, 0, --1n: [io posit"CPUT",me: shortNahnology",  Tecniversity ofninsula Ue PeCap{ name: " (9)
  OLOGYOF TECHNTIES / UNIVERSI },

  /33 }g: 31.88, ln-28.8500tes: { lat: rdinang"], cootraini"Teacher ", tyulu identi ["Strong ZFacts:notableining"], ration tEduca"s",  program ["Culturalupport:dentSstu", mpuscaitage-rich l hertura"Culfe:  campusLi",geulu herital studies, Zn, Cultura"Educatioor: , bestFion"]astal locatms", "🌊 Con prograatio🎓 Educe", "u heritag["🏛️ Zulghlights: ces", hi residenampusation: "Cmmod" }, acco0/year0,0025,000 - R6uate: "Rtgradar", pos,000/ye- R50"R35,000 rgraduate: fees: { undeber" }, "30 Septemeadline: licationD appication",vant qualifRelegraduate: "osts", por's paschel"NSC with Baduate: dergra{ uns: equirement, admissionR km/h" }d: "13"75%", winmidity: umid", hudition: "H con: "24°C",empeather: { t" }, wr: "20°CC", winte"28° { summer: , avgTemp:l coastal"btropicamate: "Su+", cli00 "16,0tudents: s",ucationStrong in edking: ", ranLaw"]ce", "", "CommerArts "tion",s: ["Educaonlizati, speciaity"versheritage uni cultural Zulucription: " desversity",ehensive Uniomprpe: "C, tylished: 1960ab", esthards Bay "Ric, city:tal""KwaZulu-Na ovince:c2626", pr "#d color: 0],[12, 0, position: ",uZul: "Uni shortNameululand",f Zniversity oame: "U
  
  { n } },28.7833.5833, lng: t: -31tes: { lanardi], coo focus"al "Ruructure",trlti-campus sacts: ["Mu notableFng"],rainith t"Healpment", velo["Rural deport: tudentSupy", ssitral univer rui-campusife: "Mult, campusLation" educRuralsciences, th : "Heal"], bestForementgagnity en"🤝 Commuucation", ral edRu"🎓 ", th sciences"🏥 Healhts: [", highligdencesmpus resii-caultdation: "M" }, accommoar R58,000/ye4,000 -aduate: "R2 postgryear", R48,000/ "R32,000 -te:graduader: { un fees" },ember"30 Sept: neeadlitionDn", applicaalificatio quvantate: "Relepostgradu", ss's paelorachSC with B: "Nrgraduates: { undeentremnRequiissioh" }, adm km/"11nd: ", wiidity: "68%d", humilndition: "M"19°C", co: { temp: ather }, we14°C""ter: win "24°C", r:{ summegTemp: perate", av "Tem climate:00+",28,0"dents: rams", stuing prog "Developranking:"], gementre", "Mana"Agricultucation",  "Eduiences", Sc"Healthns: [atiospecializ", l university-campus ruraion: "Multicriptsity", desnivere Uensivompreh5, type: "C: 200lishedha", estabhatity: "Mtape", cstern Ce: "Ea", provinc: "#7c3aed, color [8, 0, 8]ion:", posite: "WSUrtNam", shositylu Universualter Si{ name: "W 
  
 4333 } },30.: , lngat: -22.9833ates: { lcoordinn"], atioal preserv "Cultur focus",elopmental devs: ["RurotableFact"], naining tricultural"Agr", lopmentdeve ["Rural port:tSup", studenitageltural hermpus with cu ca "RuralsLife:, campue"icmunity serv Comealth,ral he, Ruurultor: "Agric bestFfordable"],"💚 Aflth", Rural hea🏥 grams", "ltural pro["🌾 Agricuhighlights: nces", resideampus tion: "On-c, accommoda0/year" }- R55,002,000 e: "R2ostgraduat, p0/year"45,00R30,000 - Rate: "ndergraduees: { u }, fmber" "30 Septeadline:ationDeon", appliclificatievant quaRelte: " postgraduas",or's pas with BachelSCte: "Nndergraduaments: { uonRequiresimis, ad/h" }nd: "7 km%", wi"60 humidity:  "Warm",ition:", cond"26°C: { temp: , weather"20°C" } winter: r: "30°C", { summevgTemp:", apical"Subtrote: +", clima"15,000nts:  studeture",n agriculowing iGring: "ranknt"], ageme, "Manon" "EducatiSciences",", "Health riculturetions: ["Aglizaeciasity", spuniverive hensl compre "Ruradescription:ity", sive Universehenmprtype: "Cohed: 1982, stablisyandou", eho"Thocity: opo", impce: "Lovinpr"#059669", color: 0, 12], ition: [12, niven", pos"UortName: , sha" of Vend"Universityme:   
  { na946 } },
lng: 28.15, .761: { lat: -25ordinates cor"],oneen piucatio edance", "Dist Africasity inverest unis: ["LargactbleF, notaters"]al cen"Region, upport"tance s: ["DisSupporttudent s centers",alionng with regance learniLife: "Dist campusonals",professig , Workinearningance l"DistestFor: le"], bAffordabeer", "💰 tance pion"🌍 Dis Africa", gest in Larights: ["📚g", highlnine learstanc"Diodation: " }, accommR50,000/year"R20,000 - uate: postgrad0/year", ,00 - R40e: "R25,000at{ undergradu" }, fees: periodsle : "MultipDeadlineapplicationation", ualific qantte: "Relev, postgraduaor's pass" with Bachele: "NSCundergraduatents: { uiremadmissionReqkm/h" }, "9 %", wind:  "50umidity: hsant","Pleadition: 21°C", con": { temp: " }, weather"16°Cter: ", win26°C summer: ", avgTemp: {nd"ghlal hiubtropicae: "S, climat,000+"ts: "400a", studenest in Afric: "Larginges"], rankniti "Huma","Education aw", "Lsiness","Buations: [specializ", tiontance educat diss largesca': "Afriescription", d Universityhensivepe: "Compred: 1873, tylishestabretoria", e "Pcity:", : "Gauteng", provinced12lor: "#7c22], co, 0, -1[0tion: isa", posiName: "Un", shortouth Africaity of Svers name: "Uni,
  
  {022 } } lng: 25.68,t: -33.960inates: { lacoordcus"], mmunity foco "Strong r Mandela","Named aftebleFacts: [e"], notanceer guidaarrams", "City progmunt: ["ComdentSupporons", stuity connecti with communastal campusife: "CoampusLent", cemngag eity Communlifestyle,stal Coaess, "BusinestFor: "], bramsusiness prognt", "💼 Bty engageme🤝 Communi, "ion"tal locatoas"🌊 C: [ghlights", hiesidencespus rtion: "Camccommoda aear" },000/y000 - R70,"R28,te: ostgradua", p/year R60,000000 -e: "R40,atraduerg { und}, fees:September" "30 ine: onDeadlapplicatition", ificaquallevant ate: "Re, postgradu"r's passith Bachelo"NSC wate: { undergradurements: sionRequi}, admis8 km/h" , wind: "170%"ity: "y", humid"Breezition: ", cond"22°C: { temp: ther }, wea18°C"inter: ""25°C", wmmer: { su, avgTemp: e coastal"atperate: "Temim00+", cl"27,0udents: nsive", st comprehe"Leadingng: rankion"], "Educatices", th Scienal", "Heering", "Engines"Businestions: [izacial spey",ituniversmprehensive oastal cotion: "Cdescripersity",  UnivrehensiveCompype: "hed: 2005, testablisizabeth",  "Port Elpe", city:astern Ca"E: vince9", pro"#05966], color: : [8, 0, -8onpositi", e: "NMUortNam", shsityndela UniverMan e: "Nelsonam
  
  { 8.0436 } },ng: 21848, llat: -26. { s:inate"], coordle locations "Multips",universitieest ne of larg ["ObleFacts:es"], notareer servic"Caries", nsive bursaehet: ["ComprtSuppor", studen universityrban"Large uampusLife: ", cexperienceban ering, Urgine, Enss "BusineestFor:eering"], b️ Engin "⚙",ng business"💼 Stros", ple campuse Multits: ["🏢highligh", ncespus resideple cam "Multition:oda accomm}," 000/year0,00 - R8 "R30,0e:raduattg, pos0/year" - R65,00"R45,000e: aduatgrder{ un}, fees: ptember"  "30 Seadline:tionDe", applicaicationant qualif "Relevostgraduate:, p"or's passelchwith BaSC te: "Nrgradua { undets:equiremendmissionRkm/h" }, a "11 %", wind:ity: "45", humidion: "ClearC", condit: "20°: { tempherat}, weC" : "16°, winter"26°C"{ summer: : , avgTempl highland"icabtropmate: "Su,000+", cli: "50studentssive", prehen"Top 5 com: ingion"], rank"EducatArts",  "Business", "g",ineerin: ["Engnsatioalizty", speciersive univnsimprehe: "Large coonti", descriptysisive Univerehen"Compr005, type: ablished: 2 estnesburg","Johanty: ", ci: "Gauteng", provincer: "#ea580c-4], coloon: [4, 0, , positiUJ""rtName: burg", shoannesrsity of Johme: "Unive)
  { naS (6IE UNIVERSITVEEHENSI COMPR//

  .0305 } }, lng: 2826.1929,s: { lat: -rdinatecooness"], usiAfrican b"Gateway to lobally", ing mining gts: ["Leadac"], notableFips partnersh "Industryrograms",rsary pport: ["BuentSup, studus"mp urban caamic: "DynpusLifeess", cam, Businningng, MieriEngineFor: "stc hub"], benomico "🏙️ Eections",connndustry "💼 I  mining",s topd': ["⛏️ Worlhts", highligampusted on-cn: "Limitioodaccommyear" }, a0,000/ - R1800,0 "R40ate:, postgradu/year"- R75,000,000 e: "R55aduatergr { undees:" }, feptember "30 SDeadline:cationpliegree", aplor's dt bachean"Relevgraduate: ", postss pachelor's with Ba: "NSCduategrants: { underiremeonRequ, admissi" } "12 km/hnd:", wi: "45%idity humy",Cloud "Partly ondition:"19°C", cp: ther: { temea°C" }, w"16nter:  wi26°C",: "mersumemp: {  avgT",dhlanropical higmate: "Subtcli", +ts: "40,000 studen",outh Africain Sing: "#2 , rank"]eeringginrce", "En", "CommeMedicineeering", "ining Engin: ["Mtionsalizaci speing",eer and enginngn minice i: "Excellen descriptionniversity",raditional U: "Type: 1922, tishedg", establurJohannesby: "g", citce: "Gautenaf", provin "#1e40r: 0, 0], colo0, position: [s",Name: "Wit, shortsrand"he Witwaterof t"University e:  nam,
  
  {} }g: 18.6341 -33.9328, lnlat: rdinates: {  coocused"],-fo"Community", tionadijustice trl : ["SociaableFacts"], noty service"Communitrograms",  justice p"Socialupport: [ studentSs",s campuconsciouly cialSoife: "usLice", campial just SocDentistry,: "Law, ], bestForengagement"munity m", "🌍 Comgraentistry prow", "🦷 Dustice laSocial jghts: ["⚖️ hlies", higpus residencam"On-cion: ccommodat}, a00/year" - R75,0"R30,000 aduate: ostgr", p/yearR65,00045,000 - "Rergraduate:  { undfees: }, " Septembere: "30inadltionDe", applicadegreeelor's ant bachelev: "Rate postgradus",r's paschelowith BaSC ate: "Ngraduunderirements: { sionRequmis, ad6 km/h" } "1wind:y: "65%", ", humiditnnyon: "Su conditi"22°C",: emp { tweather:}, "15°C" : nter°C", wi"26 { summer: ", avgTemp:iterraneanedte: "Mma", clis: "24,000+, studentin law"g: "Strong n"], rankinducatio Work", "E"Social", ry"Dentist, ["Law"ions: alizatity", speciuniversocus ce focial justion: "Sescriptity", diversional Un: "Traditi typeshed: 1960,liown", estab "Cape Tcity:ape", stern C "Weovince:d", pr "#7c3ae color:],, -5n: [-20, 0", positioName: "UWCpe", shorttern Ca Westhef  oiversitye: "Un  
  { nam2 } },
8.860g: 1ln.9321, at: -33es: { lcoordinatcampus"], tiful  "Beauh",ine researceading w"World's lableFacts: [ies"], notportunitearch op "Resies",sarultural bur ["Agrict:tudentSupporyards", snewn with vic tostori"Hife: ", campusLinge, Engineeriurulte, Agric"Wine scienc bestFor: "], settingountain, "🏔️ Mure"agricult"🌾 Top  leader",  winelobal ["🍷 Gs:", highlightem systresidenceoric on: "Histcommodatiar" }, ac0,000/ye,000 - R11R40te: ", postgraduaear"00/y,000 - R80,0"R60uate:  undergrad {fees:r" }, ptembene: "30 SeationDeadli, applic's degree"bachelor "Relevant ate:postgraduss", helor's path BacwiC  "NSe:ergraduatments: { undreuinReqadmissiokm/h" },  wind: "14 0%","6ity: ", humid "Sunnydition:23°C", con": empther: { t" }, wea5°Cwinter: "1 "27°C",  { summer:", avgTemp:diterraneanimate: "Me", cl"32,000+tudents: , sca"uth Afri: "#2 in So], ranking"Business"g", rin"Engineeure", Agricult", "e Scienceions: ["Winecializatty", sprsiikaans univefr"Leading Ation:  descripy",sitverUniional pe: "Tradit: 1918, tylishedh", establlenbosc"Stecity: e", n Caper: "Westprovince", r: "#dc2626 0], colo, 0,tion: [-15si"SU", poortName: ", shersityosch Univ: "Stellenb  
  { name },
33 }: 26.53.3167, lng -33at: ltes: {nacoordirnalism"], ier jouPremates", "tisfaction rHighest sa: ["ctsnotableFasystem"], Residence ntion", " attersonalpport: ["PetudentSus", sth traditiony town wie universit"Intimate: usLif", campes experiencall clascy, Sm Pharmaalism,Journ":  bestFor"],assesall cl👥 Smrmacy", "ing pha "💊 Leadol",rnalism scho ["📰 #1 Joughlights: histem", synceesiderehensive r "Compation:commod" }, ac00/year00 - R80,05,0: "R3ostgraduate pr", R70,000/yea "R60,000 -ate:gradues: { undert" }, fe"31 Augusadline: icationDeappls degree",  bachelor'"Relevantuate: ostgrad, p pass"'schelorSC with Bae: "Nundergraduatts: { remenonRequiadmissikm/h" }, nd: "12 5%", wi: "6humidity"Mild", n:  conditio19°C", " { temp:ther:4°C" }, weawinter: "1: "25°C", meremp: { sumte", avgT"Temperaclimate: +", 00"8,2nts: ce", studeperien student ex"Top ranking: mmerce"],", "Cowcy", "La, "Pharma"nalisms: ["Jourionlizatecia, spsity"erll univ"Premier smaiption:  descriversity",itional Un"Trad4, type: lished: 190, estabMakhanda": "", cityrn Cape: "Easteincef", prove40ar: "#1, -5], colo: [-10, 0, position"RU" me:", shortNaersity Univ"Rhodes
  { name: 4 } },
  231 28..7545, lng:: { lat: -25dinates coorch"], researnaryg veteriLeadinity", "ct universargest contas: ["LFactbleies"], notapportunit"Research os", bursarieMerit pport: ["udentSu", st capitalus inmpn carge urba"Lae: , campusLif Research"ring,e, EngineeencciVeterinary s: ""], bestForl city"🏛️ Capitang", ineering e️ Top"⚙hool", rinary sc🐾 #1 Vete: ["tsligh", highdence systemnsive resi"Exteodation: ommaccr" }, ea- R100,000/y: "R40,000 graduate post0/year",75,005,000 - R "R5e:undergraduats: {  feer" },embeSeptdline: "30 tionDeacaappli", gree's deornt bachel "Relevastgraduate:ss", pos paor'with BachelSC e: "Nuat{ undergradements: onRequirsi admis/h" },0 km: "1", windity: "50%id", humsanteaition: "PlC", cond1°emp: "2{ t}, weather: "16°C" , winter: 26°C"mer: ": { sumempland", avgTal highubtropicimate: "S cl",000+nts: "53,", studein Africarinary  "#1 Vete"], ranking:w"La", ineMedic"ineering", "Eng", cienceeterinary Sations: ["Vlizia", specversityarch uniLeading resen: "riptio descty",nal Universitio "Tradi type:ed: 1908,lishtabtoria", esPre"ty: g", cice: "Gautenovinpr, 2"c2d1color: "#70], ion: [5, 0,  positame: "UP",a", shortNPretori of "University  { name: } },
  
00 7.10: 26.7167, lng{ lat: -2: nates"], coordipusam-clti", "Muersity univ majorordablefft a: ["MosFacts"], notablebursarieseering "Engin fees", ableAffordSupport: [" studentity town",ersional univaditTrsLife: "mputy", cardable qualiAffo, ducationng, Engineerir: "EstFo"], bedableaffor"💰 Most y", lttion facu📚 Educag", "erinngine️ Strong eghts: ["⚙ highliem",yst snceive reside "Extenscommodation: }, acr"000/yea5,000 - R60, "R2ostgraduate:", p0,000/yearR35,000 - R5te: "ergradua{ und:  }, feesSeptember"line: "30 adtionDe", applicadegreelor's ant bache"Relevuate: grads", postasBachelor's p"NSC with graduate: nts: { underquiremesionRe" }, admis"15 km/hnd: "35%", wity: umidiy", hion: "Drit9°C", cond{ temp: "1, weather: "12°C" }winter: °C", "27: { summer: gTemp, av-arid" "Semiclimate:4,000+", "6dents: ", stuering engine introngking: "S, ranusiness"], "B"Theology", ation" "Educ",ngeerins: ["Enginizatioe", specialns heritagith Afrikaas wulti-campu "Miption:, descrrsity"iveitional Un"Tradtype: hed: 2004, isablesttroom", "Potchefs: st", city: "North Wence80c", provi "#ea5olor:, 0, 15], cosition: [-5NWU", pe: "Nam", shortUniversity"North-West name: 
  { } },
  g: 29.7394 23.8883, ln{ lat: -ates: oordinntered"], city-ce"Commun focus", ealthral h"RuleFacts: ["], notabninglth trais", "Heal bursariert: ["RuradentSuppostunity", ral commuse-knit ru: "ClosLifepuam, cculture"ne, Agriiciedl ms, Ruraiencescalth For: "He"], bestdableor "💚 Affearch",ural result", "🌾 AgricsciencesHealth 🏥 ["ights: ghldences", hicampus resiation: "On-commod acr" },ea- R65,000/y,000 ate: "R25graduear", post0/y00 - R55,0035,0 "Raduate:rgr { undes:" }, fee September"30line: onDead", applicatiegree d bachelor's: "Relevantduatetgrapos", lor's passwith Bache: "NSC duate undergraents: {sionRequiremis/h" }, adm8 km", wind: "y: "55%m", humiditWarndition: "co"24°C", temp: eather: { C" }, w"18°er: ", wintmer: "30°CTemp: { suml", avgopicae: "Subtrlimat,000+", cdents: "20s", stulth scienceg in heawin"Gro ranking: tion"],"Educare", "Agricultu", es Scienc"Healthns: [atiopecializ s",communitiesural serving r university "Northerncription: esity", dUniversitional Trad "05, type:hed: 20tabliseskwane", city: "Polopo", e: "Limponcrovi059669", pr: "# colo10], [15, 0, sition:: "UL", po", shortNameimpopoy of LUniversitme: "
  
  { na0218 } },g: 31. ln87,-29.85es: { lat: rdinatses"], cooiple campuMultnt", "llmeby enro"Largest Facts: [], notablee"changational ex"Internsaries", ve burmprehensiort: ["CoSupps", studenteach accesus with b campulticultural mbrantLife: "Vi, campusfestyle"liCoastal ering, inene, Eng: "MediciForstl"], belturaMulticu🌍 h", "arc reserong", "🔬 Stionocat"🌊 Coastal lhts: [ighligces", henpus residple camti"Mulodation: , accomm0/year" } R85,00"R35,000 -duate: gra post000/year",70,- R000 R50,e: "undergraduat }, fees: { er"mb Septe: "30inetionDeadl", applicadegreeelor's t bachRelevanuate: "", postgrads passhelor'BacSC with duate: "Nndergra: { utsonRequiremen" }, admissi"12 km/h5%", wind: midity: "7", huumid"Htion: °C", condi temp: "25r: {theea w" }, "20°Cter: win "28°C",{ summer:: l", avgTempopicaSubtrlimate: ", c"47,000+"nts: ica", studeh Afr in Sout "#3ng:w"], ranki"La", lturericug", "Agngineerin "EMedicine", ["s:ization", specialrse programsith diveersity wunival Coastcription: ", desrsity"tional Unive: "Tradiypeed: 2004, tish establban",y: "Dur", citlu-Natal"KwaZuvince: d", proc3ae#7 color: "5],: [10, 0, osition p "UKZN",me:", shortNa-Natal of KwaZulutyUniversi"e:  
  { nam
 } },g: 26.2167 9.1167, ln: { lat: -2tes], coordinaction"instru"Bilingual ub", icultural hor agracts: ["MajtableFnoining"], al tra, "Medics"ursarieal bltur: ["Agricuupport studentSn",ty towiversinal unTraditiofe: "", campusLi