// Complete South African Universities Database - All 26 Universities

export interface University {
  name: string;
  shortName: string;
  position: [number, number, number];
  color: string;
  province: string;
  city: string;
  established: number;
  type: "Traditional University" | "Comprehensive University" | "University of Technology";
  description: string;
  specializations: string[];
  ranking: string;
  students: string;
  climate: string;
  avgTemp: { summer: string; winter: string };
  weather: { temp: string; condition: string; humidity: string; wind: string }; // Fallback data - will be replaced by real-time API
  admissionRequirements: {
    undergraduate: string;
    postgraduate: string;
    applicationDeadline: string;
  };
  fees: { undergraduate: string; postgraduate: string };
  accommodation: string;
  highlights: string[];
  bestFor: string;
  campusLife: string;
  studentSupport: string[];
  notableFacts: string[];
  coordinates: { lat: number; lng: number };
}

export const SA_UNIVERSITIES: University[] = [ 
 // TRADITIONAL UNIVERSITIES (11)
  { name: "University of Cape Town", shortName: "UCT", position: [-15, 0, -10], color: "#1e40af", province: "Western Cape", city: "Cape Town", established: 1829, type: "Traditional University", description: "Africa's leading research university", specializations: ["Medicine", "Engineering", "Business", "Law"], ranking: "#1 in Africa", students: "29,000+", climate: "Mediterranean", avgTemp: { summer: "26°C", winter: "15°C" }, weather: { temp: "22°C", condition: "Sunny", humidity: "65%", wind: "15 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R65,000 - R85,000/year", postgraduate: "R45,000 - R120,000/year" }, accommodation: "On-campus residences available", highlights: ["🏆 Top-ranked African university", "🔬 Leading research output", "🏔️ Table Mountain views", "🌊 Close to beaches"], bestFor: "Research excellence, Medicine, International recognition", campusLife: "Vibrant cosmopolitan campus with mountain and ocean access", studentSupport: ["Financial aid", "Career services", "Academic support"], notableFacts: ["Oldest university in South Africa", "Most beautiful campus globally"], coordinates: { lat: -33.9577, lng: 18.4612 } },
  
  { name: "University of Fort Hare", shortName: "UFH", position: [-10, 0, 15], color: "#059669", province: "Eastern Cape", city: "Alice", established: 1916, type: "Traditional University", description: "Historic 'Oxford of Africa'", specializations: ["Law", "Education", "Agriculture", "Social Sciences"], ranking: "Historic significance", students: "12,000+", climate: "Temperate", avgTemp: { summer: "24°C", winter: "12°C" }, weather: { temp: "18°C", condition: "Partly Cloudy", humidity: "70%", wind: "10 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R35,000 - R45,000/year", postgraduate: "R25,000 - R55,000/year" }, accommodation: "On-campus residences", highlights: ["🎓 Alma mater of Mandela", "📚 Liberation history", "🌍 Pan-African heritage"], bestFor: "Law, Education, African studies", campusLife: "Small town with rich political history", studentSupport: ["NSFAS funding", "Academic mentoring"], notableFacts: ["Produced many African leaders", "First to admit black students"], coordinates: { lat: -32.7833, lng: 26.8500 } },
  
  { name: "University of the Free State", shortName: "UFS", position: [0, 0, 10], color: "#dc2626", province: "Free State", city: "Bloemfontein", established: 1904, type: "Traditional University", description: "Central SA university with agriculture focus", specializations: ["Agriculture", "Medicine", "Law", "Education"], ranking: "Top 5 for Agriculture", students: "37,000+", climate: "Semi-arid", avgTemp: { summer: "28°C", winter: "10°C" }, weather: { temp: "16°C", condition: "Clear", humidity: "40%", wind: "18 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R45,000 - R65,000/year", postgraduate: "R30,000 - R75,000/year" }, accommodation: "Extensive on-campus residences", highlights: ["🌾 Leading agricultural research", "⚖️ Strong law faculty", "🏥 Medical school"], bestFor: "Agriculture, Medicine, Central location", campusLife: "Traditional university town", studentSupport: ["Agricultural bursaries", "Medical training"], notableFacts: ["Major agricultural hub", "Bilingual instruction"], coordinates: { lat: -29.1167, lng: 26.2167 } },
  
  { name: "University of KwaZulu-Natal", shortName: "UKZN", position: [10, 0, 5], color: "#7c3aed", province: "KwaZulu-Natal", city: "Durban", established: 2004, type: "Traditional University", description: "Coastal university with diverse programs", specializations: ["Medicine", "Engineering", "Agriculture", "Law"], ranking: "#3 in South Africa", students: "47,000+", climate: "Subtropical", avgTemp: { summer: "28°C", winter: "20°C" }, weather: { temp: "25°C", condition: "Humid", humidity: "75%", wind: "12 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R50,000 - R70,000/year", postgraduate: "R35,000 - R85,000/year" }, accommodation: "Multiple campus residences", highlights: ["🌊 Coastal location", "🔬 Strong research", "🌍 Multicultural"], bestFor: "Medicine, Engineering, Coastal lifestyle", campusLife: "Vibrant multicultural campus with beach access", studentSupport: ["Comprehensive bursaries", "International exchange"], notableFacts: ["Largest by enrollment", "Multiple campuses"], coordinates: { lat: -29.8587, lng: 31.0218 } },
  
  { name: "University of Limpopo", shortName: "UL", position: [15, 0, 10], color: "#059669", province: "Limpopo", city: "Polokwane", established: 2005, type: "Traditional University", description: "Northern university serving rural communities", specializations: ["Health Sciences", "Agriculture", "Education"], ranking: "Growing in health sciences", students: "20,000+", climate: "Subtropical", avgTemp: { summer: "30°C", winter: "18°C" }, weather: { temp: "24°C", condition: "Warm", humidity: "55%", wind: "8 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R35,000 - R55,000/year", postgraduate: "R25,000 - R65,000/year" }, accommodation: "On-campus residences", highlights: ["🏥 Health sciences", "🌾 Agricultural research", "💚 Affordable"], bestFor: "Health sciences, Rural medicine, Agriculture", campusLife: "Close-knit rural community", studentSupport: ["Rural bursaries", "Health training"], notableFacts: ["Rural health focus", "Community-centered"], coordinates: { lat: -23.8883, lng: 29.7394 } },
  
  { name: "North-West University", shortName: "NWU", position: [-5, 0, 15], color: "#ea580c", province: "North West", city: "Potchefstroom", established: 2004, type: "Traditional University", description: "Multi-campus with Afrikaans heritage", specializations: ["Engineering", "Education", "Theology", "Business"], ranking: "Strong in engineering", students: "64,000+", climate: "Semi-arid", avgTemp: { summer: "27°C", winter: "12°C" }, weather: { temp: "19°C", condition: "Dry", humidity: "35%", wind: "15 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R35,000 - R50,000/year", postgraduate: "R25,000 - R60,000/year" }, accommodation: "Extensive residence system", highlights: ["⚙️ Strong engineering", "📚 Education faculty", "💰 Most affordable"], bestFor: "Engineering, Education, Affordable quality", campusLife: "Traditional university town", studentSupport: ["Affordable fees", "Engineering bursaries"], notableFacts: ["Most affordable major university", "Multi-campus"], coordinates: { lat: -26.7167, lng: 27.1000 } },  
  { name: "University of Pretoria", shortName: "UP", position: [5, 0, 0], color: "#7c2d12", province: "Gauteng", city: "Pretoria", established: 1908, type: "Traditional University", description: "Leading research university", specializations: ["Veterinary Science", "Engineering", "Medicine", "Law"], ranking: "#1 Veterinary in Africa", students: "53,000+", climate: "Subtropical highland", avgTemp: { summer: "26°C", winter: "16°C" }, weather: { temp: "21°C", condition: "Pleasant", humidity: "50%", wind: "10 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R55,000 - R75,000/year", postgraduate: "R40,000 - R100,000/year" }, accommodation: "Extensive residence system", highlights: ["🐾 #1 Veterinary school", "⚙️ Top engineering", "🏛️ Capital city"], bestFor: "Veterinary science, Engineering, Research", campusLife: "Large urban campus in capital", studentSupport: ["Merit bursaries", "Research opportunities"], notableFacts: ["Largest contact university", "Leading veterinary research"], coordinates: { lat: -25.7545, lng: 28.2314 } },
  
  { name: "Rhodes University", shortName: "RU", position: [-10, 0, -5], color: "#1e40af", province: "Eastern Cape", city: "Makhanda", established: 1904, type: "Traditional University", description: "Premier small university", specializations: ["Journalism", "Pharmacy", "Law", "Commerce"], ranking: "Top student experience", students: "8,200+", climate: "Temperate", avgTemp: { summer: "25°C", winter: "14°C" }, weather: { temp: "19°C", condition: "Mild", humidity: "65%", wind: "12 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "31 August" }, fees: { undergraduate: "R60,000 - R70,000/year", postgraduate: "R35,000 - R80,000/year" }, accommodation: "Comprehensive residence system", highlights: ["📰 #1 Journalism school", "💊 Leading pharmacy", "👥 Small classes"], bestFor: "Journalism, Pharmacy, Small class experience", campusLife: "Intimate university town with traditions", studentSupport: ["Personal attention", "Residence system"], notableFacts: ["Highest satisfaction rates", "Premier journalism"], coordinates: { lat: -33.3167, lng: 26.5333 } },
  
  { name: "Stellenbosch University", shortName: "SU", position: [-15, 0, 0], color: "#dc2626", province: "Western Cape", city: "Stellenbosch", established: 1918, type: "Traditional University", description: "Leading Afrikaans university", specializations: ["Wine Science", "Agriculture", "Engineering", "Business"], ranking: "#2 in South Africa", students: "32,000+", climate: "Mediterranean", avgTemp: { summer: "27°C", winter: "15°C" }, weather: { temp: "23°C", condition: "Sunny", humidity: "60%", wind: "14 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R60,000 - R80,000/year", postgraduate: "R40,000 - R110,000/year" }, accommodation: "Historic residence system", highlights: ["🍷 Global wine leader", "🌾 Top agriculture", "🏔️ Mountain setting"], bestFor: "Wine science, Agriculture, Engineering", campusLife: "Historic town with vineyards", studentSupport: ["Agricultural bursaries", "Research opportunities"], notableFacts: ["World's leading wine research", "Beautiful campus"], coordinates: { lat: -33.9321, lng: 18.8602 } },
  
  { name: "University of the Western Cape", shortName: "UWC", position: [-20, 0, -5], color: "#7c3aed", province: "Western Cape", city: "Cape Town", established: 1960, type: "Traditional University", description: "Social justice focus university", specializations: ["Law", "Dentistry", "Social Work", "Education"], ranking: "Strong in law", students: "24,000+", climate: "Mediterranean", avgTemp: { summer: "26°C", winter: "15°C" }, weather: { temp: "22°C", condition: "Sunny", humidity: "65%", wind: "16 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R45,000 - R65,000/year", postgraduate: "R30,000 - R75,000/year" }, accommodation: "On-campus residences", highlights: ["⚖️ Social justice law", "🦷 Dentistry program", "🌍 Community engagement"], bestFor: "Law, Dentistry, Social justice", campusLife: "Socially conscious campus", studentSupport: ["Social justice programs", "Community service"], notableFacts: ["Social justice tradition", "Community-focused"], coordinates: { lat: -33.9328, lng: 18.6341 } },
  
  { name: "University of the Witwatersrand", shortName: "Wits", position: [0, 0, 0], color: "#1e40af", province: "Gauteng", city: "Johannesburg", established: 1922, type: "Traditional University", description: "Excellence in mining and engineering", specializations: ["Mining Engineering", "Medicine", "Commerce", "Engineering"], ranking: "#2 in South Africa", students: "40,000+", climate: "Subtropical highland", avgTemp: { summer: "26°C", winter: "16°C" }, weather: { temp: "19°C", condition: "Partly Cloudy", humidity: "45%", wind: "12 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant bachelor's degree", applicationDeadline: "30 September" }, fees: { undergraduate: "R55,000 - R75,000/year", postgraduate: "R40,000 - R180,000/year" }, accommodation: "Limited on-campus", highlights: ["⛏️ World's top mining", "💼 Industry connections", "🏙️ Economic hub"], bestFor: "Engineering, Mining, Business", campusLife: "Dynamic urban campus", studentSupport: ["Bursary programs", "Industry partnerships"], notableFacts: ["Leading mining globally", "Gateway to African business"], coordinates: { lat: -26.1929, lng: 28.0305 } },
  // COMPREHENSIVE UNIVERSITIES (6)
  { name: "University of Johannesburg", shortName: "UJ", position: [4, 0, -4], color: "#ea580c", province: "Gauteng", city: "Johannesburg", established: 2005, type: "Comprehensive University", description: "Large comprehensive university", specializations: ["Engineering", "Business", "Arts", "Education"], ranking: "Top 5 comprehensive", students: "50,000+", climate: "Subtropical highland", avgTemp: { summer: "26°C", winter: "16°C" }, weather: { temp: "20°C", condition: "Clear", humidity: "45%", wind: "11 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R45,000 - R65,000/year", postgraduate: "R30,000 - R80,000/year" }, accommodation: "Multiple campus residences", highlights: ["🏢 Multiple campuses", "💼 Strong business", "⚙️ Engineering"], bestFor: "Business, Engineering, Urban experience", campusLife: "Large urban university", studentSupport: ["Comprehensive bursaries", "Career services"], notableFacts: ["One of largest universities", "Multiple locations"], coordinates: { lat: -26.1848, lng: 28.0436 } },
  
  { name: "Nelson Mandela University", shortName: "NMU", position: [8, 0, -8], color: "#059669", province: "Eastern Cape", city: "Port Elizabeth", established: 2005, type: "Comprehensive University", description: "Coastal comprehensive university", specializations: ["Business", "Engineering", "Health Sciences", "Education"], ranking: "Leading comprehensive", students: "27,000+", climate: "Temperate coastal", avgTemp: { summer: "25°C", winter: "18°C" }, weather: { temp: "22°C", condition: "Breezy", humidity: "70%", wind: "18 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R40,000 - R60,000/year", postgraduate: "R28,000 - R70,000/year" }, accommodation: "Campus residences", highlights: ["🌊 Coastal location", "🤝 Community engagement", "💼 Business programs"], bestFor: "Business, Coastal lifestyle, Community engagement", campusLife: "Coastal campus with community connections", studentSupport: ["Community programs", "Career guidance"], notableFacts: ["Named after Mandela", "Strong community focus"], coordinates: { lat: -33.9608, lng: 25.6022 } },
  
  { name: "University of South Africa", shortName: "Unisa", position: [0, 0, -12], color: "#7c2d12", province: "Gauteng", city: "Pretoria", established: 1873, type: "Comprehensive University", description: "Africa's largest distance education", specializations: ["Business", "Law", "Education", "Humanities"], ranking: "Largest in Africa", students: "400,000+", climate: "Subtropical highland", avgTemp: { summer: "26°C", winter: "16°C" }, weather: { temp: "21°C", condition: "Pleasant", humidity: "50%", wind: "9 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant qualification", applicationDeadline: "Multiple periods" }, fees: { undergraduate: "R25,000 - R40,000/year", postgraduate: "R20,000 - R50,000/year" }, accommodation: "Distance learning", highlights: ["📚 Largest in Africa", "🌍 Distance pioneer", "💰 Affordable"], bestFor: "Distance learning, Working professionals", campusLife: "Distance learning with regional centers", studentSupport: ["Distance support", "Regional centers"], notableFacts: ["Largest university in Africa", "Distance education pioneer"], coordinates: { lat: -25.7615, lng: 28.1946 } },
  
  { name: "University of Venda", shortName: "Univen", position: [12, 0, 12], color: "#059669", province: "Limpopo", city: "Thohoyandou", established: 1982, type: "Comprehensive University", description: "Rural comprehensive university", specializations: ["Agriculture", "Health Sciences", "Education", "Management"], ranking: "Growing in agriculture", students: "15,000+", climate: "Subtropical", avgTemp: { summer: "30°C", winter: "20°C" }, weather: { temp: "26°C", condition: "Warm", humidity: "60%", wind: "7 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R30,000 - R45,000/year", postgraduate: "R22,000 - R55,000/year" }, accommodation: "On-campus residences", highlights: ["🌾 Agricultural programs", "🏥 Rural health", "💚 Affordable"], bestFor: "Agriculture, Rural health, Community service", campusLife: "Rural campus with cultural heritage", studentSupport: ["Rural development", "Agricultural training"], notableFacts: ["Rural development focus", "Cultural preservation"], coordinates: { lat: -22.9833, lng: 30.4333 } },
  
  { name: "Walter Sisulu University", shortName: "WSU", position: [8, 0, 8], color: "#7c3aed", province: "Eastern Cape", city: "Mthatha", established: 2005, type: "Comprehensive University", description: "Multi-campus rural university", specializations: ["Health Sciences", "Education", "Agriculture", "Management"], ranking: "Developing programs", students: "28,000+", climate: "Temperate", avgTemp: { summer: "24°C", winter: "14°C" }, weather: { temp: "19°C", condition: "Mild", humidity: "68%", wind: "11 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R32,000 - R48,000/year", postgraduate: "R24,000 - R58,000/year" }, accommodation: "Multi-campus residences", highlights: ["🏥 Health sciences", "🎓 Rural education", "🤝 Community engagement"], bestFor: "Health sciences, Rural education", campusLife: "Multi-campus rural university", studentSupport: ["Rural development", "Health training"], notableFacts: ["Multi-campus structure", "Rural focus"], coordinates: { lat: -31.5833, lng: 28.7833 } },
  
  { name: "University of Zululand", shortName: "UniZulu", position: [12, 0, 0], color: "#dc2626", province: "KwaZulu-Natal", city: "Richards Bay", established: 1960, type: "Comprehensive University", description: "Zulu cultural heritage university", specializations: ["Education", "Arts", "Commerce", "Law"], ranking: "Strong in education", students: "16,000+", climate: "Subtropical coastal", avgTemp: { summer: "28°C", winter: "20°C" }, weather: { temp: "24°C", condition: "Humid", humidity: "75%", wind: "13 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R35,000 - R50,000/year", postgraduate: "R25,000 - R60,000/year" }, accommodation: "Campus residences", highlights: ["🏛️ Zulu heritage", "🎓 Education programs", "🌊 Coastal location"], bestFor: "Education, Cultural studies, Zulu heritage", campusLife: "Cultural heritage-rich campus", studentSupport: ["Cultural programs", "Education training"], notableFacts: ["Strong Zulu identity", "Teacher training"], coordinates: { lat: -28.8500, lng: 31.8833 } },
  
  // UNIVERSITIES OF TECHNOLOGY (9)
  { name: "Cape Peninsula University of Technology", shortName: "CPUT", position: [-18, 0, -8], color: "#ea580c", province: "Western Cape", city: "Cape Town", established: 2005, type: "University of Technology", description: "Leading technology university", specializations: ["Engineering", "IT", "Design", "Business"], ranking: "Top University of Technology", students: "32,000+", climate: "Mediterranean", avgTemp: { summer: "26°C", winter: "15°C" }, weather: { temp: "22°C", condition: "Sunny", humidity: "65%", wind: "15 km/h" }, admissionRequirements: { undergraduate: "NSC with Diploma pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R40,000 - R55,000/year", postgraduate: "R28,000 - R65,000/year" }, accommodation: "Campus residences", highlights: ["⚙️ Technology programs", "💻 IT and design", "🏙️ Multiple campuses"], bestFor: "Engineering technology, IT, Design", campusLife: "Modern technology campuses", studentSupport: ["Industry partnerships", "Practical training"], notableFacts: ["Largest University of Technology", "Industry connections"], coordinates: { lat: -33.9249, lng: 18.4241 } },
  
  { name: "Central University of Technology", shortName: "CUT", position: [2, 0, 12], color: "#dc2626", province: "Free State", city: "Bloemfontein", established: 1981, type: "University of Technology", description: "Central technology university", specializations: ["Engineering", "IT", "Management", "Health Sciences"], ranking: "Strong in engineering", students: "14,000+", climate: "Semi-arid", avgTemp: { summer: "28°C", winter: "10°C" }, weather: { temp: "16°C", condition: "Clear", humidity: "40%", wind: "18 km/h" }, admissionRequirements: { undergraduate: "NSC with Diploma pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R35,000 - R50,000/year", postgraduate: "R25,000 - R55,000/year" }, accommodation: "Campus residences", highlights: ["⚙️ Engineering technology", "💻 IT facilities", "💰 Affordable"], bestFor: "Engineering technology, IT, Practical skills", campusLife: "Technology-focused campus", studentSupport: ["Technical training", "Industry partnerships"], notableFacts: ["Strong technical focus", "Central location"], coordinates: { lat: -29.1167, lng: 26.2167 } },
  
  { name: "Durban University of Technology", shortName: "DUT", position: [14, 0, 4], color: "#7c3aed", province: "KwaZulu-Natal", city: "Durban", established: 2002, type: "University of Technology", description: "Coastal technology university", specializations: ["Engineering", "IT", "Management", "Applied Sciences"], ranking: "Leading in KZN", students: "29,000+", climate: "Subtropical", avgTemp: { summer: "28°C", winter: "20°C" }, weather: { temp: "25°C", condition: "Humid", humidity: "75%", wind: "12 km/h" }, admissionRequirements: { undergraduate: "NSC with Diploma pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R38,000 - R52,000/year", postgraduate: "R26,000 - R60,000/year" }, accommodation: "Campus residences", highlights: ["🌊 Coastal location", "⚙️ Engineering programs", "🏭 Industry partnerships"], bestFor: "Engineering technology, Coastal lifestyle", campusLife: "Modern coastal campus", studentSupport: ["Industry partnerships", "Practical training"], notableFacts: ["Strong industry connections", "Coastal focus"], coordinates: { lat: -29.8587, lng: 31.0218 } },
  
  { name: "Mangosuthu University of Technology", shortName: "MUT", position: [16, 0, 2], color: "#059669", province: "KwaZulu-Natal", city: "Umlazi", established: 1979, type: "University of Technology", description: "Community-focused technology university", specializations: ["Engineering", "IT", "Management Sciences"], ranking: "Growing technology", students: "12,000+", climate: "Subtropical", avgTemp: { summer: "28°C", winter: "20°C" }, weather: { temp: "24°C", condition: "Warm", humidity: "72%", wind: "11 km/h" }, admissionRequirements: { undergraduate: "NSC with Diploma pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R32,000 - R45,000/year", postgraduate: "R24,000 - R52,000/year" }, accommodation: "Campus residences", highlights: ["🤝 Community focus", "⚙️ Engineering programs", "🌍 Local development"], bestFor: "Community technology, Engineering", campusLife: "Community-centered campus", studentSupport: ["Community programs", "Technical training"], notableFacts: ["Strong community focus", "Local development"], coordinates: { lat: -29.9667, lng: 30.8833 } },
  
  { name: "Tshwane University of Technology", shortName: "TUT", position: [6, 0, 2], color: "#7c2d12", province: "Gauteng", city: "Pretoria", established: 2004, type: "University of Technology", description: "Large multi-campus technology university", specializations: ["Engineering", "IT", "Management", "Arts & Design"], ranking: "Largest by enrollment", students: "60,000+", climate: "Subtropical highland", avgTemp: { summer: "26°C", winter: "16°C" }, weather: { temp: "21°C", condition: "Pleasant", humidity: "50%", wind: "10 km/h" }, admissionRequirements: { undergraduate: "NSC with Diploma pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R36,000 - R48,000/year", postgraduate: "R26,000 - R58,000/year" }, accommodation: "Multiple campus residences", highlights: ["🏢 Multiple campuses", "⚙️ Engineering", "🎨 Arts & design"], bestFor: "Engineering technology, IT, Arts", campusLife: "Large multi-campus university", studentSupport: ["Technical training", "Industry partnerships"], notableFacts: ["Largest University of Technology", "Multiple campuses"], coordinates: { lat: -25.7545, lng: 28.2314 } },
  
  { name: "Vaal University of Technology", shortName: "VUT", position: [2, 0, 6], color: "#059669", province: "Gauteng", city: "Vanderbijlpark", established: 1966, type: "University of Technology", description: "Industrial technology university", specializations: ["Engineering", "IT", "Management Sciences"], ranking: "Strong in industrial", students: "20,000+", climate: "Subtropical highland", avgTemp: { summer: "26°C", winter: "14°C" }, weather: { temp: "18°C", condition: "Mild", humidity: "48%", wind: "13 km/h" }, admissionRequirements: { undergraduate: "NSC with Diploma pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R34,000 - R46,000/year", postgraduate: "R25,000 - R54,000/year" }, accommodation: "Campus residences", highlights: ["🏭 Industrial connections", "⚙️ Engineering programs", "🔧 Practical skills"], bestFor: "Industrial engineering, Manufacturing", campusLife: "Industrial region campus", studentSupport: ["Industrial partnerships", "Technical training"], notableFacts: ["Strong industrial focus", "Manufacturing connections"], coordinates: { lat: -26.7167, lng: 27.8333 } },
  
  { name: "University of Mpumalanga", shortName: "UMP", position: [8, 0, 14], color: "#dc2626", province: "Mpumalanga", city: "Nelspruit", established: 2014, type: "University of Technology", description: "Newest technology university", specializations: ["Agriculture", "Engineering", "IT", "Education"], ranking: "New with growing programs", students: "5,000+", climate: "Subtropical", avgTemp: { summer: "28°C", winter: "18°C" }, weather: { temp: "23°C", condition: "Pleasant", humidity: "58%", wind: "9 km/h" }, admissionRequirements: { undergraduate: "NSC with Diploma pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R30,000 - R42,000/year", postgraduate: "R22,000 - R48,000/year" }, accommodation: "New campus residences", highlights: ["🌱 Newest university", "🌾 Agricultural focus", "⚙️ Modern facilities"], bestFor: "Agriculture, New programs", campusLife: "New modern campus", studentSupport: ["New programs", "Modern facilities"], notableFacts: ["Newest university", "Provincial development"], coordinates: { lat: -25.4753, lng: 30.9694 } },
  
  { name: "Sol Plaatje University", shortName: "SPU", position: [-8, 0, 18], color: "#ea580c", province: "Northern Cape", city: "Kimberley", established: 2014, type: "University of Technology", description: "New comprehensive university", specializations: ["Education", "Natural Sciences", "Humanities", "Data Sciences"], ranking: "New innovative programs", students: "3,000+", climate: "Semi-arid", avgTemp: { summer: "30°C", winter: "12°C" }, weather: { temp: "20°C", condition: "Dry", humidity: "35%", wind: "16 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass", postgraduate: "Relevant qualification", applicationDeadline: "30 September" }, fees: { undergraduate: "R28,000 - R38,000/year", postgraduate: "R20,000 - R45,000/year" }, accommodation: "New campus residences", highlights: ["🌟 Newest comprehensive", "💎 Diamond city", "📊 Data sciences"], bestFor: "Education, Data sciences, New programs", campusLife: "Brand new campus", studentSupport: ["New programs", "Modern technology"], notableFacts: ["Second newest university", "Named after Sol Plaatje"], coordinates: { lat: -28.7282, lng: 24.7499 } },
  
  { name: "Sefako Makgatho Health Sciences University", shortName: "SMU", position: [4, 0, 16], color: "#16a34a", province: "Gauteng", city: "Pretoria", established: 2014, type: "Traditional University", description: "Specialized health sciences university", specializations: ["Medicine", "Dentistry", "Pharmacy", "Health Sciences", "Nursing"], ranking: "Leading health sciences", students: "4,000+", climate: "Subtropical highland", avgTemp: { summer: "26°C", winter: "16°C" }, weather: { temp: "21°C", condition: "Pleasant", humidity: "50%", wind: "10 km/h" }, admissionRequirements: { undergraduate: "NSC with Bachelor's pass, high requirements for health sciences", postgraduate: "Relevant bachelor's degree, professional registration", applicationDeadline: "30 September" }, fees: { undergraduate: "R45,000 - R75,000/year", postgraduate: "R35,000 - R85,000/year" }, accommodation: "Limited on-campus, medical student housing", highlights: ["🏥 Specialized health focus", "💊 Leading pharmacy school", "🦷 Excellent dentistry", "👩‍⚕️ Top nursing programs"], bestFor: "Health sciences, Medicine, Dentistry, Specialized healthcare", campusLife: "Health-focused campus with clinical training facilities", studentSupport: ["Health bursaries", "Clinical training", "Professional development"], notableFacts: ["Newest health sciences university", "Strong clinical partnerships", "Specialized medical focus"], coordinates: { lat: -25.7308, lng: 28.1731 } }
];